markdown: kramdown
kramdown:
  extensions:   ["with_toc_data"]
permalink: /:year/:month/:title/
url: http://chenhongbiao.github.io/cn
homepage: http://chenhongbiao.github.io/
author: 陈宏标
highlighter: pygments

