markdown:       redcarpet
redcarpet:
  extensions:   ["with_toc_data"]
permalink: /:year/:month/:title/
url: http://chenhongbiao.github.com/cn
homepage: http://chenhongbiao.github.com
author: 陈宏标
highlighter: pygments

